### ISSUE TITLE
API Script Down

### ISSUE THREAD

**Issue by harisnaeemofficial** [Jaydeep-01/godfather.vip#1]
Why is this API down now http://api.godfather.vip:3030/api/downloader/?ch=1565176158&id=3

Where we can get this API script to make it online?

Can you help me to make it work again, please?

**Comment by Jaydeep-01** [comment]
It's not about the API down, I have shut down the server and put the whole project on sale. I cannot share more details about it in this thread. For more info please contact to my mail.
